name:                domain-modeling-made-functional
version:             0.1.0.0
github:              "githubuser/domain-modeling-made-functional"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/domain-modeling-made-functional#readme>

dependencies:
- base >= 4.7 && < 5
- basement
- text

library:
  source-dirs: src

executables:
  domain-modeling-made-functional-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - domain-modeling-made-functional

tests:
  domain-modeling-made-functional-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - domain-modeling-made-functional
